[package]
name = "iaik-master-projetc-template"
version = "1.0.0"
entrypoint = "./src/lib.typ"
authors = ["csskevin", "ecomaikgolf"]
license = "MIT"
description = "IAIK Master Project Template"

[template]
path = "./"
entrypoint = "demo.typ"
