[package]
name = "iaik-master-project-template"
version = "1.0.0"
entrypoint = "./src/lib.typ"
authors = ["csskevin", "ecomaikgolf"]
license = "MIT"
description = "IAIK Master Project Template"

[template]
path = "template"
entrypoint = "project.typ"
